### ISSUE TITLE
detailed error message

### ISSUE THREAD

**Issue by BSVogler** [Dineshkarthik/Whatsapp-analyzer#1]
Hi!
Interesting project. It is the most promising one on GitHub. The other ones are broken, without explanation or hard to install. However I get an internal server error after I uploaded my script. How can I debug this?

Kind regards,
Benedikts

**Comment by Dineshkarthik** [comment]
Hi,

I have mentioned this in the ReadMe section under Known Issues.
Depending on your OS and version of Whatsapp, the format of text file lines varies wildly.

The regex in the code takes `dd/mm/yy, hh:mm AM`.
Regex used in line `39` & `41`.
Any other format will throw error.

Coming to the issue.
To enable the error message change `debug=True` in the following line

```
app.run(host='0.0.0.0', debug=False, port=int(options.port))
```
